config/routes.rb
Grooobiz::Application.routes.draw do
  resources :locations

  resources :categories

  resources :companies

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
      get :revoke_role, :on => :member
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
    mount_uploader :logo, LogoUploader

    has_and_belongs_to_many :users
    has_and_belongs_to_many :categories
    belongs_to :location

    @@roles = %w{principal angel investor}
    
    def allowed_roles
        @@roles
    end

    # generate accessor methods for all roles listed in @@roles 
    # example: @company.principals, @company.has_angels?
    def self.add_role_methods
        @@roles.each do |role|
            define_method(role.to_s.pluralize) { get_users_by_role(role) } 
            define_method(%Q(has_#{role}s?)) { send(role).count > 0}
        end
    end
    add_role_methods

    # there should be only one owner per company
    def owner 
        get_users_by_role( :owner ).first
    end 

    def category_list 
        categories.map{ |cat| cat.name }.join(', ')
    end

    def assign_categories=(categories)
        logger.debug 'inside assign_categories=', categories

        categories.split(',').map do |category| 
            cat = Category.find_or_create_by(name: category.strip) 
            self.categories << cat unless @company.categories.include?(cat)
        end

    end


    private 
    def get_users_by_role( role )
        User.all.find_all { |user| user.has_role? role, self }
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!, except: :home

    # GET /companies
    # GET /companies.json
    def index
        @companies = Company.all
    end

    # GET /companies/1
    # GET /companies/1.json
    def show
    end

    # GET /companies/new
    def new
        @company = Company.new

        @company.categories = []
        @company.location = Location.new
        @company.logo = params[:logo] if params[:logo]
    end

    # GET /companies/1/edit
    def edit
    end

    # POST /companies
    # POST /companies.json
    def create
        categories = process_categories
        location = process_location
        @company = Company.new(company_params)
        @company.categories = categories
        @company.location = location
        
        @company.logo = params[:logo] if params[:logo]

        respond_to do |format|
            if @company.save
                # person who created the company is assigned :owner and :principal roles by default 
                current_user.add_role :owner, @company
                current_user.add_role :principal, @company

                format.html { redirect_to @company, notice: 'Company was successfully created.' }
                format.json { render action: 'show', status: :created, location: @company }
            else
                format.html { render action: 'new' }
                format.json { render json: @company.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /companies/1
    # PATCH/PUT /companies/1.json
    def update
        @company.logo = params[:logo] if params[:logo]
        
        if company_params.has_key?('add_role')
            user = User.find(company_params['id'])
            user.add_role( company_params['add_role'], @company ) if user
            
            redirect_to edit_company_path # , notice: user.name + ' added to company as ' + company_params['add_role'].to_s.capitalize
        else
            respond_to do |format|
                @company.categories = process_categories
                @company.location = process_location if 'true' == params[:location][:dirty]
                
                if @company.update(company_params)
                    format.html { redirect_to @company, notice: 'Company was successfully updated.' }
                    format.json { head :no_content }
                else
                    format.html { render action: 'edit' }
                    format.json { render json: @company.errors, status: :unprocessable_entity }
                end
            end
        end
    end

    # DELETE /companies/1
    # DELETE /companies/1.json
    def destroy
    
        @company.destroy
        respond_to do |format|
            format.html { redirect_to companies_url }
            format.json { head :no_content }
        end
    end

    
    protected
    def process_location
        Location.find_or_create_by(name: params[:location][:name])
    end
    
    def process_categories
        params[:company].delete(:category_list)
            .split(',')
            .map { |category| Category.find_or_create_by(name: category.strip) }
    end
    

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
        @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
        params.
            require(:company).
            permit( :user_id, 
                    :name, 
                    :description, 
                    :tagline, 
                    :audience, 
                    :launch_date, 
                    :add_role, 
                    :id, 
                    :location,
                    :category_list,
                    :logo )
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_add_role.erb
<%= form_for @company do |f| %>
<%= f.hidden_field :add_role, :value => role %>
<%= f.collection_select :id, 
	User.all.find_all { |user| !user.has_role? role, @company }, # only users who don't already have role/company
	:id, 
	:name, 
	{ :include_blank => true },
	{ :class => 'select ' + role } 
%>
<%= f.submit 'Add ' + role.to_s.capitalize %>
<% end %> 

app/views/companies/_edit_delete_links.erb
<div style='float:right;'>
	<span><%= link_to 'Edit', edit_company_path(company) %> &nbsp;</span>
	<span><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></span>
</div>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
	<% if @company.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>
		<ul>
			<% @company.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<div>Company Name</div>
		<%= f.text_field :name, :placeholder => 'Company Name' %>
	</div>

	<div class="field">
		<div>Tagline / Pitch</div>
		<%= f.text_field :tagline, :placeholder => 'Tagline (or Pitch)' %>
	</div>
	<div class="field">
		<div>Description</div>
		<%= f.text_area :description, :placeholder => 'Description' %>
	</div>
	<div class="field">
		<div>Audience</div>
		<%= f.text_field :audience, :placeholder => 'Audience' %>
	</div>

<!-- TODO: convert to Month/Year picker -->
<div class="field">
	<div>Launch Date</div>
	<%= f.text_field :launch_date, :placeholder => 'Launch Date' %>
</div>

<!-- TODO: convert this from simple text field to lookup UI --> 
<div class="field">
<%= fields_for @company.location do |location_fields| %>
	<div>Location</div>
	<%= location_fields.text_field :name, 
		:placeholder => 'Location (such as: London, UK)', 
		:onchange => "$('#location_dirty').val(this.defaultValue != this.value.trim());" %>
	<%= location_fields.hidden_field :dirty, :value => false %>
<% end %>
</div>

<!-- TODO: convert this to rendering individual x-to-delete (like angels etc) items -->
<!-- 	   this will allow removal of 'def category_list' on Company model -->
<!-- 	   but will require a new add model -->
<div class="field">
	<div>Categories</div>
	<%= f.text_field :category_list, :placeholder => 'Categories (comma-separated)' %>
</div>
<div class="field">
	<%= f.label :logo %><br />
	<%= f.file_field :logo %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/companies/_show_attribute.erb
<style>
	.company-attribute-label {
		font-weight: bold;
		margin-bottom: 0.2em;
	}
	.company-attribute-value {
		margin-bottom: 1em;
	}
</style>

<div class='company-attribute-label'>
	<%= local_assigns[:label].nil? ? 
		attribute.capitalize : 
		label %>
</div>
<div class='company-attribute-value'>
	<%= !local_assigns[:value].nil? ? 
		value : 
		!local_assigns[:capture].nil? ? 
			capture : 
			@company.send(attribute) %>
</div>

app/views/companies/_users_by_role.html.erb
<%
role = locals[:role] 
invalid_role_message = "Unrecognized role '" + role + "'. Allowed roles => " + @company.allowed_roles.to_s
raise(RuntimeError, invalid_role_message) if !@company.allowed_roles.include?(role)

action = params['action']
role_pluralized = role.pluralize
%>
<div id='<%= %Q(users_by_role_#{role}) %>' class='<%= %Q(role #{role}) %>'>
	<strong><%= role_pluralized.capitalize %></strong>
	<ul>
	<% companies = @company.send(role_pluralized) %>
	<% if companies.count > 0 %>
		<% companies.each do |user|  %>
		<li id='<%= %Q(#{user.id}_#{@company.id}_#{role}) %>'>
		<%= link_to user.name, user %>
		<% if action == 'edit' %>
		<%= link_to 'x', 
				revoke_role_user_path(user.id, company_id: @company.id, role: role),
				remote: true, 
				title: :Remove
		%>
		<% end %>
		</li>
		<% end %>	
	<% else %>
		<li>None</li>
	<% end %>
	</ul>
</div>

<% if action == 'edit' %>
<%= render 'add_role', :role => role %>
<% end %>

app/views/companies/edit.html.erb
<h3><%= @company.name %></h3>

<div style='vertical-align:top;'>
	<span style='width:30%; display:inline-block; vertical-align:top; float:right;'>
		<% @company.allowed_roles.each do |role| %> 
		<%= render 'users_by_role', :locals => { :role => role } %>
		<% end %>
	</span>
	<span style='width:58%; display:inline-block;'>
		<%= render 'form' %>
	</span>
</div>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h3>Listing companies</h3>

<% @companies.each do |company| %>
<div style='border-bottom:1px solid #333;'>
	<% if current_user.can_edit?(company) %>
	<div style='float:right;'>
		<span><%= link_to 'Edit', edit_company_path(company) %> &nbsp;</span>
		<span><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></span>
	</div>
	<% end %>
	<h4 style='display:inline;'><%= link_to company.name, company %></h4>
</div>
<div><%= company.description %></div>
<br/>
<% end %>

<br/>
<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<% if current_user.can_edit? @company %>
<div class="table">
	<div class="row">
		<span class="cell">
			<%= image_tag @company.logo.url %>
		</span>
		<span class="cell">
			<h4><%= @company.name %></h4>
			<span>Launched <%= @company.launch_date %></span>
		</span>
		<span class="cell">
			<%= link_to 'Edit', edit_company_path(@company) %> 
			<% end %>
		</span>
	</div>
</div>

<hr/>

<span style='width:20%; float:right; margin-left:5em;'>
	<% @company.allowed_roles.each do |role| %> 
	<%= render 'users_by_role', :locals => { :role => role } %>
	<% end %>
</span>

<span>
	<%= render 'show_attribute', 
				:attribute => :tagline %>
	<%= render 'show_attribute', 
				:attribute => :description %>
	<%= render 'show_attribute', 
				:attribute => :audience %>
	<%= render 'show_attribute', 
				:attribute => :location, 
				:value => @company.location.name %>
	<%= render 'show_attribute', 
				:label => 'Categories', 
				:capture => capture { %>
					<% @company.categories.each do |cat| %>
					<%= link_to cat.name, cat %><%= ', ' if cat != @company.categories.last %>
					<% end %>
	<% } %>
</span>